### ISSUE TITLE
Move the Joi validation to the controllers directory to its own file

### ISSUE THREAD

**Issue by pouyapourbaba** [msm-faraj/ToDoList#15]
The controllers should reside in their own folder. After creating a folder called `controllers` move the `todo-controller` there. Moreover, create a new file called `todo-validator` and move the todo validation method from the controller and write the newly created file.

**Comment by msm-faraj** [comment]
a folder with controller name is created and todo-controller moved into that folder.  Also todo-validator is moved to the modules folder. 
plus these, Todo  model and validator function added as parameter to the controller class.
